name: PanVK Builder CI

on:
  workflow_dispatch:

jobs:
  build-panvk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip \
            meson \
            ninja-build \
            patchelf \
            unzip \
            curl \
            flex \
            bison \
            zip \
            glslang-tools \
            ccache
          pip3 install mako

      - name: Run builder script
        run: |
          chmod +x ./turnip_builder.sh
          ./turnip_builder.sh

      - name: Upload build logs
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: |
            turnip_workdir/meson_log.txt
            turnip_workdir/ninja_log.txt

      - name: Upload Magisk Module
        uses: actions/upload-artifact@v4
        with:
          name: panvk_magisk
          path: turnip_workdir/panvk_magisk.zip

      - name: Upload Adrenotools Package
        uses: actions/upload-artifact@v4
        with:
          name: panvk_adrenotools
          path: turnip_workdir/panvk_adrenotools.zip
